services:
  db:
    image: mysql:8.0
    container_name: inventoryms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ohonbiz@10
      MYSQL_DATABASE: InventoryMs
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - inventory_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventoryms_backend
    ports:
      - "7028:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=InventoryMs;User=root;Password=ohonbiz@10;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - inventory_network

  frontend:
    build:
      context: ../inventory-frontend
      dockerfile: Dockerfile
    container_name: inventoryms_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - inventory_network

volumes:
  mysql_data:

networks:
  inventory_network:
    driver: bridge
